### ISSUE TITLE
Error Windows 7 x64 python 2.7.8

### ISSUE THREAD

**Issue by xiva-wgt** [dashea/requests-file#1]
Hello!
Error Windows 7 x64 python 2.7.8

Error Windows 7 x64 python 2.7.8
    resp_str = str(e).encode(locale.nl_langinfo(locale.CODESET))
AttributeError: 'module' object has no attribute 'nl_langinfo'

maybe better to use '.encode(locale.getpreferredencoding())' to resolve this error?

**Comment by dashea** [comment]
Sure, will do.
