### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by anarcat** [dashea/requests-file#10]
Hi,

For your information, I am working on packaging this library for debian. You can follow the progress of this effort in [#879125](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879125) on the Debian BTS. if you are interested in maintaining the package yourself upstream, that's also a possibility, especially if you are a debian maintainer or developer. if not, I can also act as a sponsor when a new release is published.

This is just a notification, but can also act as a coordination point for upstream packaging if you wish to followup on this. otherwise, feel free to close this issue whenever you like.

Thank you for your attention.

**Comment by dashea** [comment]
Thanks for packaging it, but I'm not interested in maintaining the Debian package.
