### ISSUE TITLE
Please made adapter cross-platform - a variant solution in ticket.

### ISSUE THREAD

**Issue by xiva-wgt** [dashea/requests-file#2]
file-adapter don't download on windows.
if 'path_parts = [unquote(p) for p in url_parts.path.split('/')]'
replace to
'drive, filepath = os.path.splitdrive(url_parts.path)
path_parts = [unquote(p) for p in filepath.replace('\\', '/').split('/')]'
and
'path_parts[0] = os.sep'
replace to
'path_parts[0] = drive + os.sep'
file-adapter work on windows and unix-like system.
thanks in advance, best regards

**Comment by dashea** [comment]
I need to read a little more about this one, and see if I can dig up a Windows system to test some things. At a glance I think I'll also need to look for the different ways that windows file:// URLs can encode the drive part, like for example, c|/path/to/file.

**Comment by dashea** [comment]
Sorry that took so long. Tested in with both 2 and 3 on XP, and making into a new release now.
