### ISSUE TITLE
Bug : requests-file not supporting web framework errors - leads to xss vulnerability

### ISSUE THREAD

**Issue by MindPatch** [dashea/requests-file#20]
##### _if you have any error in python web frameworks, the server will be send (500 : internal error error) in the response without print the error name or code_ **(without debugging Mode)**
<h5> here im using requests module to send http request</h5>

 ### _with error_ : 
#### you can't find the errors in your code (without debugging Mode)
* Error in Flask Framework
![errr](https://user-images.githubusercontent.com/45688522/81969979-134a2400-961f-11ea-801b-ae0f820ae3c5.png)
* Error in tornado Framework
![ter_err](https://user-images.githubusercontent.com/45688522/81975116-d8e48500-9626-11ea-8ad0-15371de0283a.png)

### without error  : 
* Flask Framework
![without_errr](https://user-images.githubusercontent.com/45688522/81970134-51474800-961f-11ea-9d15-3da784345035.png)

* tornado Framework
![ter_no](https://user-images.githubusercontent.com/45688522/81975236-029dac00-9627-11ea-9e68-6d2687a970be.png)

## with error : 
* Flask Framework
![err_req](https://user-images.githubusercontent.com/45688522/81970562-04b03c80-9620-11ea-9bd9-8a9862c539e4.png)

* tornado Framework
![ter_err_f](https://user-images.githubusercontent.com/45688522/81975529-7770e600-9627-11ea-8ef2-a09ba914a1a8.png)
### now the attacker can be use this error for XSS Attacks because The error was printed on the page without any filter
* Flask Framework
![xss_req](https://user-images.githubusercontent.com/45688522/81970957-9b7cf900-9620-11ea-853c-69afff0dfd32.png)
* tornado Framework
![ter_xss](https://user-images.githubusercontent.com/45688522/81976549-fdd9f780-9628-11ea-9be7-e45e157a205b.png)

hmmm let's try to add xss payload in requests like requests-file
* Flask Framework
![no_xss](https://user-images.githubusercontent.com/45688522/81976742-4a253780-9629-11ea-84a8-f4103d0b3e54.png)
* tornado Framework
![ter_no_xss](https://user-images.githubusercontent.com/45688522/81976867-72ad3180-9629-11ea-9353-3a5e01e19295.png)

why i can't find any xss like requests-file .?
 * because requests module supporting web errors not like requests-file
## impact : 
**now All requests-file users(web dev) are vulnerable to this attack (XSS),With the help of xss a hacker or attacker can perform social engineering on users by redirecting them from real website to fake one.
hacker can steal their cookies and download a malware on their system, and there are many more attacking scenarios a skilled attacker can perform with xss.**

**Comment by dashea** [comment]
Thanks for the report! I think I get the gist of the problem--the existence or non-existence of local files is being exposed to outside users--but I don't understand how thing should be changed in requests-file. Is there a way that requests-file is interacting with the underlying requests library that needs to be changed? Basically, this seems to me like a problem to be solved in the frameworks using requests-file and not requests-file itself. Exposing the filesystem through a web framework is dangerous in itself, and I don't see how the error messages returned by the file adaptor are themselves the problem.

If there anything I can change in regards to how I'm interacting with the underlying requests library, please let me know.

Regards,
David

**Comment by MindPatch** [comment]
hi @dashea 

> requests-file is interacting with the underlying requests library that needs to be changed?

 yeah because `requests` without `requests-file` it supports web framework errors

in this screenshot im using requests without requests-file and i got error 
my web app sen't 500 in the response
<img src='https://user-images.githubusercontent.com/45688522/81976742-4a253780-9629-11ea-84a8-f4103d0b3e54.png'>

but with requests-file you can see the error in the page

<img src='https://user-images.githubusercontent.com/45688522/81975529-7770e600-9627-11ea-8ef2-a09ba914a1a8.png'>

<hr>

> Exposing the filesystem through a web framework is dangerous in itself

yeah but if the user not use it with security knowing .
you can use it for read file from directory 
for example : 
```python

def req_file(link):
	s = requests.Session()
	s.mount('file://', FileAdapter())
	resp = s.get(f'file:///{link}')
	return resp
@app.route('/') # without security problem 
def show_files():
     file_name = request.args.get('file')
     path = '/server_path/{username}/' # all files of user
     return req_file(path+file_name).content

@app.route('/s') # with security problem
def show_file():
     file_name = request.args.get('file')
     return req_file(file_name).content
```

security problems are not with modules but with user usage

you can use requests with dangerous scenario
### SSRF vulnerability
```python
@app.route('/')
def show_website():
       r = request.args.get('u')
       r = requests.get(r)
       return r.content
```

<hr>

> I don't see how the error messages returned by the file adaptor are themselves the problem.

all problem with `requests-file` the error messages not like the usual `requests` error

### requests error without `requests-file`
![req_1](https://user-images.githubusercontent.com/45688522/82144494-4e2ea080-9847-11ea-99f1-2e5f16e64bad.png)

you can see all paths and error name and you can add the error in the exception (`try & except`)

### requests error with `requests-file`
![req_2](https://user-images.githubusercontent.com/45688522/82144626-74ecd700-9847-11ea-85d9-5677c6ab0cb5.png)

no paths and error name for exception

ok this error for user he is can read it but for python no errors here and contiune in the work (this reason for bug in the web app)

now the developer can't add any errors for exception :|

>  I can change in regards to how I'm interacting with the underlying requests library, please let me know.

*  use except for errors and replace it from usual error to simple message  ❌
*  use raise for add your own errors like any module ✅

about raise : https://www.programiz.com/python-programming/user-defined-exception


Regards
Khaled

**Comment by dashea** [comment]
You're comparing entirely differently different things. Requests on its own (without requests-file) is returning a representation of an HTTP response. If an HTTP server responds that a file is not found, you'll get a 404 response object, not an exception.

```
>>> import requests
>>> resp = requests.get("http://github.com/not-a-path")
>>> print(resp)
<Response [404]>
```

If the error happens earlier and it is not possible to read a response from the server, such as if the URL if invalid or if the host is not reachable, the request attempt will raise an exception. With requests-file, since there is no remote host and no network calls, exceptions of this sort will generally not happen. If a file is not found, it will return a 404 response object to simulate a file not being found on a remote server.

This is not a security bug in requests-file. requests-file is returning HTTP responses in the same manner as requests, but there are fewer failure paths in requests-file since it treats the local filesystem as the HTTP server. If you're going to connect a web framework directly to your local filesystem you need to validate the requests and responses.
