### ISSUE TITLE
Code quality improvement

### ISSUE THREAD

**Issue by theRealProHacker** [dashea/requests-file#24]
https://github.com/dashea/requests-file/blob/f3d5f8f724767075854d3d657875e658bbff9a74/requests_file.py#L90-L95
I just saw this code and I asked myself if it wouldn't be better to replace that with this
```python
resp.status_code = (
    codes.forbidden
    if e.errno == errno.EACCES
    else codes.not_found
    if e.errno == errno.ENOENT
    else codes.bad_request
)
``` 
_Formatted with black_

Or just make a dictionary
```python
io2http = {
    errno.EACCES: codes.forbidden,
    errno.ENOENT: codes.not_found,
}
io2http.get(e.errno, codes.bad_request)
```

**Comment by dashea** [comment]
> ```python
> resp.status_code = (
>     codes.forbidden
>     if e.errno == errno.EACCES
>     else codes.not_found
>     if e.errno == errno.ENOENT
>     else codes.bad_request
> )
> ```

I find this less readable, to be honest. Any longer expression with ternary operators get confusing quick. I have a hard time just looking at it and figuring out which part is the conditional and which part is the result.

Besides that I think the ternary conditional in python is kind of gross? It's reminiscent of perl's statement modifiers and just feels kind of weird and backwards for what it's doing.

> Or just make a dictionary

That could make sense to allow the error to response mapping to grow in the future, but that's unlikely to happen. And as it is having a dictionary of two elements (plus the exception case living outside of the dictionary) seems unnecessary.

**Comment by theRealProHacker** [comment]
I just made a pull-request anyways and you can decide.
