### ISSUE TITLE
Name file include spec symbol not correct parse.

### ISSUE THREAD

**Issue by xiva-wgt** [dashea/requests-file#3]
Hello!
Sample local url 'url = 'file:///C:/blabla/ru.plus.launcher_2.0_TESTBUILD#5_4_minAPI14.apk''
Special characters available in the file name https://support.microsoft.com/en-us/kb/177506 section "MORE INFORMATION"
'#' good symbol

path_parts = [unquote(p) for p in url_parts.path.split('/')]

replace to

url_parts_path = url_parts.path
if url_parts.fragment:
    url_parts_path += '#' + url_parts.fragment
path_parts = [unquote(p) for p in url_parts_path.path.split('/')]

thanks in advance, best regards

**Comment by dashea** [comment]
The '#' character can be used in a file name, yes, but it cannot be part of a file name in a URL. This is the case even in windows. From https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

```
The username, password, and port components of a file URI in Windows are not used. In IE, including any of these components means you won’t be able to navigate to the URI. In contrast, the query and fragment components may be used. The query component will not be used when locating the resource, but the application that displays the content from the file URI may use the query component. For example, if an html document contains script, the script may read the query component of its URI when accessed via the file scheme. Similarly, the fragment will be used like a fragment in any other URI scheme.
```

In short, the query and fragment portions of the URL are used for application-specific information. requests_file is therefore correct in ignoring them.

If you need a literal # in the URL you will need to encode it as %23.
