### ISSUE TITLE
Please provide a wheel (.whl) release

### ISSUE THREAD

**Issue by MrMino** [dashea/requests-file#30]
Hi 👋

It looks like this library does not provide a pre-built binary distribution file (a `.whl`) on PyPI. Version 2.0 provides an sdist only (a .tar.gz). Installation from sdists requires installing of all specified build tools.

Since this library contains only `.py` source files, it should be pretty straightforward to generate a wheel - `pip wheel --no-deps requests-file` should be sufficient.

Could you upload a wheel for 2.0 release? Pretty please ️:)

**Comment by dashea** [comment]
Done.
