### ISSUE TITLE
Windows paths with driver letters not supported

### ISSUE THREAD

**Issue by FelixSchwarz** [dashea/requests-file#31]
I'm trying to use `requests-file` on Windows using an absolute path like this: `"file://C:/foo/bar"`.

The problem is that the current code uses `urlparse()` and `.netloc` contains `"C:"` in that case which triggers an exception:

https://github.com/dashea/requests-file/blob/829eceaca285e64a8579691577ab59ad4821b53d/requests_file.py#L36

Just to demonstrate the problem:
```
>>> from requests.compat import urlparse
>>> urlparse('file://C:/foo/bar')
ParseResult(scheme='file', netloc='C:', path='/foo/bar', params='', query='', fragment='')
```

Background: I'm trying to add [support for local repositories in conda-lock](https://github.com/conda/conda-lock/pull/538) and that project tries to support also Windows users.

Do you think we could add a workaround to support Windows drive letters? (just on Windows)

**Comment by dashea** [comment]
Hi. There are a handful of ways to express windows paths containing drive letters as file URIs. This is not one of them. Two /'s after the `file:` indicates that the next component is a hostname, which is allowed in the file URI format for certain platform-specific non-local file locations, and that isn't what you want here.

Here's how the urlparse results look using a few of the examples from [RFC 8089](https://datatracker.ietf.org/doc/html/rfc8089):

```python
>>> urlparse('file:///C:/foo/bar')
ParseResult(scheme='file', netloc='', path='/C:/foo/bar', params='', query='', fragment='')
>>> urlparse('file:///C|/foo/bar')
ParseResult(scheme='file', netloc='', path='/C|/foo/bar', params='', query='', fragment='')
>>> urlparse('file:C:/foo/bar')
ParseResult(scheme='file', netloc='', path='C:/foo/bar', params='', query='', fragment='')
```

There is handling for both the C: and C| style of drive letters in URIs. Hope this helps.

**Comment by FelixSchwarz** [comment]
Doh - somehow I missed that. Thank you very much for the explanation.
