### ISSUE TITLE
FileAdapter send does not set response.request

### ISSUE THREAD

**Issue by sturmf** [dashea/requests-file#32]
### The problem
FileAdapter Response does not set the response.request field. 

This is e.g. required in policy/actions.py:340 in method _is_method_allowed of requests-cache:
```headers = request.headers or CaseInsensitiveDict()```

I am now not 100% sure if that is required to be set by requests-file or if it is ok to be None and requests-cache should check for that.
But at least from the requests docu it seems to be mandatory.

### Environment
- requests-cache version: 1.2.0
- Python version: 3.10.12
- Platform: Ubuntu 22.04.3 LTS

**Comment by dashea** [comment]
Will tag and release to pypi as soon as I remember how to do that.

**Comment by dashea** [comment]
Quicker than usual this time. It's official. https://pypi.org/project/requests-file/2.1.0/
